package com.vn.payments.entity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Represents an Invoice entity. This class is mapped to the "invoices" table in the database.
 */
@Entity
@Table(name = "invoices")
public class Invoice {

    // Unique identifier for the invoice, auto-generated by the database
    @Id
    @GeneratedValue(generator = "UUID")
    private UUID id;

    // The total amount of the invoice
    private BigDecimal amount;

    // The amount that has been paid towards the invoice. Defaults to 0.
    private BigDecimal paidAmount = BigDecimal.ZERO;

    // The date when the invoice is due
    private LocalDate dueDate;

    // The status of the invoice (e.g., "pending", "paid", "void")
    private String status = "pending";

    // Default constructor required by JPA
    public Invoice() {
    }

    /**
     * Constructor for creating a new Invoice.
     * @param amount The total amount of the invoice.
     * @param dueDate The due date of the invoice.
     */
    public Invoice(BigDecimal amount, LocalDate dueDate) {
        this.amount = amount;
        this.dueDate = dueDate;
    }

    // Getters and Setters
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public BigDecimal getPaidAmount() {
        return paidAmount;
    }

    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}